# -*- coding: utf-8 -*-
"""Generate_Answers_AllenNLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_dS5kBXIMJ5RO-qaqvEX-p8c04i7L-B
"""

from allennlp.predictors.predictor import Predictor
import allennlp_models.rc

def Allen():
  predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bidaf-elmo.2021-02-11.tar.gz")
  return predictor

def get_Answers_Allen(question,context):
  
  predictor = Allen()
  ans = predictor.predict(
      passage=context,
      question=question)
  answer = ans["best_span_str"]
  return answer